TigerReportsSupports:
  Version: 1.7+ spigot
  Author: MrTigreroux
  Description: Adds supports to TigerReports plugin / Ajoute des supports au plugin TigerReports.
Config:
  Discord:
    Enabled: false
    Token: <token>
    # Discord bot token / Token du bot Discord
    Channel: 0
    # Text Channel ID for the alerts / Identifiant du canal texte pour les alertes
    Managers: none
#     - pseudo#1234
    # List of Discord users who can use /tigerreports command / Liste des utilisateurs du Discord qui peuvent utiliser la commande /tigerreports
    ServerInfo: yes
    # Display the server in alerts / Afficher le serveur dans les alertes
    PlayingStatus: "Minecraft server"
    # Set the played game message (the activity "Playing at ...") on Discord / Définit le jeu actuellement joué (l'activité "Joue à ...") sur Discord