TigerReportsSupports:
  Version: 1.7+ spigot
  Author: MrTigreroux
  Description: Adds supports to TigerReports plugin / Ajoute des supports au plugin TigerReports.
Config:
  Discord:
    Enabled: false
    
    Token: <token>
    # Discord bot token / Token du bot Discord
    
    Channel: 0
    # Text Channel ID for the alerts / Identifiant du canal texte pour les alertes
    
    Managers: none
#     - pseudo#1234
    # List of Discord users who can use /tigerreports command / Liste des utilisateurs du Discord qui peuvent utiliser la commande /tigerreports
    
    ServerInfo: yes
    # Display the server in alerts / Afficher le serveur dans les alertes
    
    Thumbnail: ""
    # Web link of the image displayed at the top right corner of the bot alerts / Lien internet de l'image affichée dans le coin supérieur droit des alertes du bot
    # Usable placeholders:    _Reporter_ and _Reported_
    
    PlayingStatus: "Minecraft server"
    # Set the played game message (the activity "Playing at ...") on Discord / Définit le jeu actuellement joué (l'activité "Joue à ...") sur Discord
    
    NotifyOnlyLocalReports: no
    # Notify with the Discord bot only the reports that are sent from the Spigot server where this TigerReportsSupports plugin is installed. Enabling this setting allows to install TigerReportsSupports plugin on all your Spigot servers, which is not necessary if you use BungeeCord but removes the necessity to have at least 1 connected player to receive BungeeCord notifications and therefore new reports / Informer, avec le bot Discord, uniquement des signalements envoyés depuis le serveur Spigot où ce plugin TigerReportsSupports est installé. En activant ce paramètre, le plugin TigerReportsSupports peut être installé sur tous les serveurs Spigot, ce qui n'est pas nécessaire si vous utilisez BungeeCord mais cela retire la nécessité d'avoir au moins 1 joueur connecté pour recevoir les notifications BungeeCord et donc les nouveaux signalements