name: TigerReportsSupports
version: 1.6.2
description: Adds supports to TigerReports plugin / Ajoute des supports au plugin TigerReports.
author: MrTigreroux
main: fr.mrtigreroux.tigerreportssupports.TigerReportsSupports
depend: [TigerReports]