name: TigerReportsSupports
version: 1.6.13
api-version: 1.13
description: Adds supports to TigerReports plugin / Ajoute des supports au plugin TigerReports.
author: MrTigreroux
main: fr.mrtigreroux.tigerreportssupports.TigerReportsSupports
depend: [TigerReports]